name: Multi-RDP

on:
  workflow_dispatch:
    inputs:
      instance_count:
        description: 'Number of RDP instances to create'
        required: true
        default: '5'

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]
      fail-fast: false
      max-parallel: 5

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          # Remove any existing firewall rule
          netsh advfirewall firewall delete rule name="RDP-Tailscale" 2>$null
          
          # Allow incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389

          # Restart the Remote Desktop service
          Restart-Service -Name TermService -Force
          Write-Host "RDP configured successfully"

      - name: Create RDP User
        run: |
          $username = "RDP"
          $password = "Khizar@123"
          
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          # Remove user if exists
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
              Remove-LocalUser -Name $username -Force
              Write-Host "Existing user removed"
          }
          
          # Create new user
          New-LocalUser -Name $username -Password $securePass -AccountNeverExpires -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
          
          Write-Host "User '$username' created successfully"

      - name: Download Comet Browser
        run: |
          # Create Downloads directory if it doesn't exist
          $downloadPath = "C:\Downloads"
          if (-not (Test-Path $downloadPath)) {
              New-Item -ItemType Directory -Path $downloadPath -Force | Out-Null
              Write-Host "Created Downloads directory"
          }
          
          # Download Comet Browser installer
          $cometUrl = "https://github.com/muntahajamil001/per/releases/download/V2/comet_installer_latest.exe"
          $installerPath = "$downloadPath\comet_installer_latest.exe"
          
          Write-Host "Downloading Comet Browser from GitHub..."
          Write-Host "URL: $cometUrl"
          Write-Host "Saving to: $installerPath"
          
          try {
              Invoke-WebRequest -Uri $cometUrl -OutFile $installerPath -ErrorAction Stop
              Write-Host "✓ Download completed successfully"
              
              # Verify file exists and show size
              if (Test-Path $installerPath) {
                  $fileSize = (Get-Item $installerPath).Length / 1MB
                  Write-Host "✓ File verified: $([math]::Round($fileSize, 2)) MB"
              }
          } catch {
              Write-Error "Failed to download Comet Browser: $_"
              exit 1
          }

      - name: Install Comet Browser
        run: |
          $installerPath = "C:\Downloads\comet_installer_latest.exe"
          
          if (-not (Test-Path $installerPath)) {
              Write-Error "Installer not found at $installerPath"
              exit 1
          }
          
          Write-Host "Installing Comet Browser..."
          Write-Host "Installer path: $installerPath"
          
          # Create master_preferences file to skip setup screens
          $installDir = "${env:ProgramFiles(x86)}\Comet\Application"
          $prefsContent = @"
          {
            "browser": {
              "check_default_browser": false,
              "show_home_button": true
            },
            "distribution": {
              "skip_first_run_ui": true,
              "show_welcome_page": false,
              "import_bookmarks": false,
              "import_history": false,
              "suppress_first_run_bubble": true,
              "do_not_create_desktop_shortcut": false,
              "do_not_create_quick_launch_shortcut": false,
              "do_not_create_taskbar_shortcut": false,
              "do_not_launch_chrome": true,
              "do_not_register_for_update_launch": false,
              "make_chrome_default": false,
              "make_chrome_default_for_user": false,
              "system_level": true,
              "verbose_logging": true
            },
            "first_run_tabs": []
          }
          "@
          
          # Try silent installation with various flags
          Write-Host "Starting silent installation..."
          try {
              Start-Process -FilePath $installerPath -ArgumentList "/S", "/silent", "--no-first-run", "--do-not-launch-chrome", "--system-level" -Wait -NoNewWindow
              Write-Host "✓ Installation process completed"
          } catch {
              Write-Warning "Installation with silent flags had issues, trying basic install..."
              Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait -NoNewWindow
          }
          
          # Wait for installation to complete
          Start-Sleep -Seconds 15
          
          # Create master_preferences if install directory exists
          if (Test-Path $installDir) {
              $prefsContent | Out-File -FilePath "$installDir\master_preferences" -Encoding UTF8 -Force
              Write-Host "✓ Created master_preferences file to skip setup"
          }
          
          Write-Host "✓ Comet Browser installation completed"
          Write-Host "Note: Installer kept at C:\Downloads\comet_installer_latest.exe for easy access"

      - name: Create Desktop Shortcuts
        run: |
          # Create shortcut for all users
          $publicDesktop = [Environment]::GetFolderPath("CommonDesktopDirectory")
          $rdpUserDesktop = "C:\Users\RDP\Desktop"
          
          # Find Comet Browser executable
          $possiblePaths = @(
              "${env:ProgramFiles}\Comet\Application\comet.exe",
              "${env:ProgramFiles(x86)}\Comet\Application\comet.exe",
              "${env:LocalAppData}\Comet\Application\comet.exe",
              "${env:ProgramFiles}\Comet Browser\comet.exe"
          )
          
          $cometExe = $null
          foreach ($path in $possiblePaths) {
              if (Test-Path $path) {
                  $cometExe = $path
                  Write-Host "Found Comet Browser at: $path"
                  break
              }
          }
          
          if (-not $cometExe) {
              Write-Warning "Comet Browser executable not found in standard locations"
              # List all installed programs for debugging
              Get-ChildItem "C:\Program Files" -Directory | Select-Object Name | Write-Host
              Get-ChildItem "C:\Program Files (x86)" -Directory | Select-Object Name | Write-Host
          } else {
              # Create shortcut function
              $WshShell = New-Object -ComObject WScript.Shell
              
              # Create shortcut on Public Desktop
              $shortcutPath = "$publicDesktop\Comet Browser.lnk"
              $shortcut = $WshShell.CreateShortcut($shortcutPath)
              $shortcut.TargetPath = $cometExe
              $shortcut.WorkingDirectory = Split-Path $cometExe
              $shortcut.Description = "Comet Browser"
              $shortcut.Save()
              Write-Host "Created shortcut on Public Desktop: $shortcutPath"
              
              # Create shortcut on RDP user desktop
              if (-not (Test-Path $rdpUserDesktop)) {
                  New-Item -ItemType Directory -Path $rdpUserDesktop -Force | Out-Null
              }
              $rdpShortcutPath = "$rdpUserDesktop\Comet Browser.lnk"
              $rdpShortcut = $WshShell.CreateShortcut($rdpShortcutPath)
              $rdpShortcut.TargetPath = $cometExe
              $rdpShortcut.WorkingDirectory = Split-Path $cometExe
              $rdpShortcut.Description = "Comet Browser"
              $rdpShortcut.Save()
              Write-Host "Created shortcut on RDP user Desktop: $rdpShortcutPath"
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Write-Host "Downloading Tailscale..."
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          
          Write-Host "Installing Tailscale..."
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          
          Remove-Item $installerPath -Force
          Write-Host "Tailscale installed successfully"

      - name: Connect to Tailscale
        run: |
          $hostname = "rdp-instance-${{ matrix.instance }}-run-${{ github.run_number }}"
          Write-Host "Connecting to Tailscale with hostname: $hostname"
          
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=$hostname
          
          # Wait for IP assignment
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 15) {
              Start-Sleep -Seconds 3
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              $retries++
              Write-Host "Attempt $retries : Waiting for Tailscale IP..."
          }
          
          if (-not $tsIP) {
              Write-Error "Failed to get Tailscale IP"
              exit 1
          }
          
          Write-Host "Tailscale IP assigned: $tsIP"
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
          echo "HOSTNAME=$hostname" >> $env:GITHUB_ENV
      
      - name: Verify RDP Connection
        run: |
          Write-Host "Verifying RDP on $env:TAILSCALE_IP..."
          
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389 -WarningAction SilentlyContinue
          
          if ($testResult.TcpTestSucceeded) {
              Write-Host "✓ RDP port is accessible"
          } else {
              Write-Warning "RDP port test failed, but continuing..."
          }

      - name: Keep Instance Running
        run: |
          Write-Host ""
          Write-Host "═══════════════════════════════════════════════"
          Write-Host "  RDP INSTANCE ${{ matrix.instance }} - READY"
          Write-Host "═══════════════════════════════════════════════"
          Write-Host "  Hostname : $env:HOSTNAME"
          Write-Host "  IP Address : $env:TAILSCALE_IP"
          Write-Host "  Username : RDP"
          Write-Host "  Password : Khizar@123"
          Write-Host "  Comet Browser : Installed on Desktop"
          Write-Host "═══════════════════════════════════════════════"
          Write-Host ""
          
          $counter = 0
          while ($true) {
              $counter++
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Host "[$timestamp] Instance ${{ matrix.instance }} Active (Heartbeat #$counter)"
              Start-Sleep -Seconds 300
          }
